- type: latheRecipePack
  id: ServiceBoardsEuphoria
  recipes:
  - MilkingMachineCircuitboard

- type: latheRecipePack
  id: ServiceJanitorBoardsEuphoria
  recipes:
  - PortablePumpMachineCircuitBoard # Froniter - Portal scrubber
