using Content.Shared._Floof.Language;
using Content.Shared._Floof.Language.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuEntry : PanelContainer
{
    public event Action? OnChosen;
    public event Action? OnMoveUp;
    public event Action? OnMoveDown;

    public readonly LanguagePrototype? Language;
    public bool CanChoose { get; private set; } = true;
    public int Index { get; private set; } = 1;

    public LanguageMenuEntry(LanguagePrototype language)
    {
        Language = language;
        RobustXamlLoader.Load(this);

        NameLabel.Text = language.Name;
        DescriptionLabel.SetMessage(language.Description);

        ChatPrefixLabel.Visible = language.ChatPrefix is not null;
        if (language.ChatPrefix is {} prefix)
            ChatPrefixLabel.Text = $"chat prefix: {SharedLanguageSystem.ChatPrefixChar}{prefix}";

        ChooseButton.OnPressed += _ => OnChosen?.Invoke();
        MoveUpButton.OnPressed += _ => OnMoveUp?.Invoke();
        MoveDownButton.OnPressed += _ => OnMoveDown?.Invoke();
    }

    public void SetCanChoose(bool canChoose)
    {
        ChooseButton.Disabled = !canChoose;
        CanChoose = canChoose;
    }

    /// <summary>
    ///     Set the index of this entry and specify how many entries there are. Used to disable move up/down buttons and provide a chat prefix.
    /// </summary>
    public void SetIndex(int index, int count)
    {
        Index = index;

        MoveUpButton.Disabled = index == 0;
        MoveDownButton.Disabled = index == count - 1;

        ChatPrefixAltLabel.Text = $"alt. prefix: {SharedLanguageSystem.ChatPrefixChar}{index + 1}";
    }
}

