using Content.Client._Floof.Language.Systems;
using Content.Shared._Floof.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Floof.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    // I hate. But I don't want to bother delegating CanLocalPlayerSpeak and such.
    public LanguageSystem? ClientLanguageSystem;

    private readonly List<LanguageMenuEntry> _entries = new();

    public event Action<LanguagePrototype>? OnLanguageChosen;
    public event Action<LanguagePrototype>? OnLanguageMoveUp;
    public event Action<LanguagePrototype>? OnLanguageMoveDown;

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(ProtoId<LanguagePrototype> currentLanguage, List<ProtoId<LanguagePrototype>> spokenLanguages)
    {
        var langName = Loc.GetString($"language-{currentLanguage}-name");
        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language", ("language", langName));

        OptionsList.RemoveAllChildren();
        _entries.Clear();

        for (var i = 0; i < spokenLanguages.Count; i++)
        {
            var language = spokenLanguages[i];
            var entry = AddLanguageEntry(language);
            entry?.SetIndex(i, spokenLanguages.Count);
            // Disable the button for the currently chosen language
            if (entry is not null && entry.CanChoose)
                entry.SetCanChoose(entry.Language?.ID != currentLanguage.Id);
        }
    }

    private LanguageMenuEntry? AddLanguageEntry(ProtoId<LanguagePrototype> language)
    {
        var proto = ClientLanguageSystem?.GetLanguagePrototype(language);
        if (proto is null || ClientLanguageSystem == null)
            return null;

        var entry = new LanguageMenuEntry(proto);
        entry.SetCanChoose(ClientLanguageSystem.CanLocalPlayerSpeak(language));

        entry.OnChosen += () => OnLanguageChosen?.Invoke(proto);
        entry.OnMoveUp += () => OnLanguageMoveUp?.Invoke(proto);
        entry.OnMoveDown += () => OnLanguageMoveDown?.Invoke(proto);

        OptionsList.AddChild(entry);
        _entries.Add(entry);

        return entry;
    }
}
