#!/usr/bin/env python3
# Disclaimer: this script was originally generated by an LLM and heavily modified by me for the sole purpose of extracting sock sprites out of bunnysuits
#
# This script does the following:
# - For each target image, computes (target & mask) and (target & ~mask).
# - Saves the masked part to a separate file (path change is hardcoded in get_masked_filename).
# - If there's no icon.png next to where the masked part was saved, generates it by cropping the masked part and offsetting it.
# - Overwrites the original with the unmasked part.
# - Updates meta.json's copyright field if present.
#
# It may be possible to re-use it to convert other clothing, but you'll need to:
# 1. Update the copyright append
# 2. Change the code of get_masked_filename to match your directory structure
# 3. Change the code of create_icon_for_masked to match your sprites
# 4. Provide an image mask (white pixels = separate from target image, transparent = keep), see example mask.png i used in mine
#
# The script relies on the PIL library for image processing. You may need to install it via pip. Tested on python 3.14.6
#
# Invocation example:
# > python ./Socks/separate_suits_into_socks.py Socks/mask.png Suits/*/equipped-INNERCLOTHING.png
# (note: calling from the parent directory of Socks and Suits)

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

# appended to the copyright field in meta.json
COPYRIGHT_APPEND = " | modified by Mnemotechnician - removed leotard sprites, socks are now separate clothing entities."


def get_masked_filename(original_path) -> Path:
    """Generate the sibling filename for the masked output."""
    p = Path(original_path)
    # Hardcoded path change from Suits/*/ to Socks/*/
    # Yeah i dont want to waste time making this customizable.
    return p.parent.parent.parent / "Socks" / p.parent.stem / (p.stem + ".png")

def create_blank_image(ref_img) -> Image.Image:
    """Create a blank image with the same mode and size as ref_img."""
    mode = ref_img.mode
    size = ref_img.size

    # ss14 sprites are RGBA, original code tried to preserve old mode for some reason
    if mode != 'RGBA':
        raise ValueError(f"Unsupported image mode: {mode}")

    return Image.new('RGBA', size, (0, 0, 0, 0))


def create_icon_for_masked(sprite_path) -> None:
    """Takes the resulting masked image (socks equipped- sprite) and makes an icon for it by cropping it to 32x32"""
    icon_path = Path(sprite_path).parent / "icon.png"
    if icon_path.is_file():
        print(f"{icon_path} already exists, skipping.")
        return

    # socks aren't perfectly centered
    # luckily we can just cut a rectangle a bit lower than the first state and it'll still look just fine
    y_offset = 8

    img = Image.open(sprite_path)
    icon = img.crop((0, y_offset, 32, 32 + y_offset))
    icon.save(icon_path)

def process_target(mask_img, target_path) -> None:
    """Process a single target image."""
    target_path = Path(target_path)
    if not target_path.is_file():
        print(f"Warning: {target_path} not found, skipping.")
        return

    # Open target
    try:
        img = Image.open(target_path)
    except Exception as e:
        print(f"Error opening {target_path}: {e}")
        return

    # Ensure mask is same size
    if img.size != mask_img.size:
        print(f"Warning: {target_path} size {img.size} != mask size {mask_img.size}. Skipping.")
        return

    # Check if the result already exists to support re-runs
    masked_path = get_masked_filename(target_path)
    if masked_path.is_file():
        print(f"Skipping generating a masked image for {masked_path} as it already exists")
        create_icon_for_masked(masked_path)
        return

    # Create blank background image of same mode
    transparent = create_blank_image(img)

    # Compute masked region (target & mask)
    masked = Image.composite(img, transparent, mask_img)
    # Compute unmasked region (target & ~mask)
    mask_inv = Image.eval(mask_img, lambda x: 255 - x)
    unmasked = Image.composite(img, transparent, mask_inv)

    # Save masked output
    Path(masked_path).parent.mkdir(parents=True, exist_ok=True) # mkdirs
    masked.save(masked_path)
    print(f"Saved masked region to {masked_path}")
    create_icon_for_masked(masked_path)

    # Overwrite original with unmasked
    unmasked.save(target_path)
    print(f"Overwrote {target_path} with unmasked region")

    # Update meta.json if present
    meta_path = target_path.parent / "meta.json"
    if meta_path.is_file():
        try:
            with open(meta_path, 'r', encoding='utf-8') as f:
                meta = json.load(f)
        except Exception as e:
            print(f"Error reading {meta_path}: {e}")
            return

        # Update copyright field
        if 'copyright' not in meta:
            print(f"Malformed meta.json: {meta_path}")
            return

        if COPYRIGHT_APPEND in meta['copyright']:
            print(f"Skipping {meta_path} as it already contains the appended string.")
            return

        try:
            meta['copyright'] += COPYRIGHT_APPEND
            with open(meta_path, 'w', encoding='utf-8') as f:
                json.dump(meta, f, indent=2, ensure_ascii=False)

            print(f"Updated copyright in {meta_path}")
        except Exception as e:
            print(f"Error writing {meta_path}: {e}")

def main():
    parser = argparse.ArgumentParser(
        description="Apply a mask to images: save masked part, overwrite original with unmasked. Also updates meta.json copyright and generates icon.png if not present."
    )
    parser.add_argument("mask", help="Path to the mask image (must be same dimensions as targets)")
    parser.add_argument("targets", nargs="+", help="List of target image files")
    args = parser.parse_args()

    # Load and prepare mask
    try:
        mask = Image.open(args.mask).convert('RGBA')
    except Exception as e:
        print(f"Error loading mask {args.mask}: {e}")
        sys.exit(1)

    for t in args.targets:
        process_target(mask, t)

if __name__ == "__main__":
    main()
