- type: entity # Floofstation
  name: pomegranate
  parent: FoodProduceBase
  id: FoodPomegranate
  description: A delicious, sweet fruit, believed to have special properties.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
    - spooky
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 40
        reagents:
        - ReagentId: Pomelustine
          Quantity: 30
        - ReagentId: Nutriment
          Quantity: 10
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/pomegranate.rsi
  - type: Produce
    seedId: pomegranate
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePomegranate
        Quantity: 20
  - type: SliceableFood
    count: 2
    slice: FoodPomegranateSlice
  - type: Tag
    tags:
    - Fruit

- type: entity # Floofstation
  name: pomegranate slice
  parent: ProduceSliceBase
  id: FoodPomegranateSlice
  description: A delicious, sweet fruit, believed to have special properties.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
    - spooky
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/pomegranate.rsi
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Pomelustine
          Quantity: 15
        - ReagentId: Nutriment
          Quantity: 5
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: JuicePomegranate
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
    - Slice

- type: entity
  name: humpshroom
  parent: FoodProduceBase
  id: FoodHumpShroom
  description: A sweet-smelling mushroom that excretes a sticky and arousing liquid.
  components:
  - type: FlavorProfile
    flavors:
    - mushroom
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Philterex
          Quantity: 5
        - ReagentId: Cum
          Quantity: 20
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/humpshroom.rsi
  - type: Produce
    seedId: humpShroom
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: breedshroom
  parent: FoodProduceBase
  id: FoodBreedShroom
  description: An overwhelmingly smelling mushroom that excretes an incredibly sticky and arousing liquid. It has been known to increase the population in colonies.
  components:
  - type: FlavorProfile
    flavors:
    - mushroom
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 30
        reagents:
        - ReagentId: Libidozenithizine
          Quantity: 2
        - ReagentId: Cum
          Quantity: 20
        - ReagentId: Philterex
          Quantity: 4
        - ReagentId: Happiness
          Quantity: 4
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/breedshroom.rsi
  - type: Produce
    seedId: breedShroom
  - type: Extractable
    grindableSolutionName: food
  - type: Tag
    tags:
    - Vegetable

- type: entity
  name: coconut
  parent: FoodProduceBase
  id: FoodCoconut
  description: A delicious, sweet fruit, believed to have special properties.
  components:
  - type: FlavorProfile
    flavors:
    - sweet
    - creamy
    - nutty
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 7
        reagents:
        - ReagentId: CoconutWater
          Quantity: 2
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/coconut.rsi
  - type: Produce
    seedId: coconut
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: CoconutWater
        Quantity: 10
  - type: Tag
    tags:
    - Fruit
    - CoconutFruit
  - type: DamageOtherOnHit
    damage:
      types:
        Blunt: 1 # give it a tiny bit of throw damage for the silly

- type: entity
  name: coconut gun husk
  parent: FoodProduceBase
  id: FoodCoconutGunFruit
  description: A delicious, gun-shaped fruit with a thick wooden stem.
  components:
  - type: FlavorProfile
    flavors:
    - gunpowder
    - sweet
    - creamy
    - nutty
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Sulfur # we keep this so it tastes similar to gat fruit
          Quantity: 5
        - ReagentId: CoconutWater
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/coconut_gun.rsi
  - type: Produce
    seedId: coconutgun
  - type: Edible
    trash:
    - WeaponRifleCoconutGun
  - type: Butcherable
    butcheringType: Knife
    spawned:
    - id: WeaponRifleCoconutGun
  - type: Tag
    tags:
    - Fruit # It's in the name

- type: entity
  name: peanut
  parent: FoodProduceBase
  id: FoodPeanutInShell # in shell
  description: A delicious and salty peanut in its shell.
  components:
  - type: FlavorProfile
    flavors:
    - creamy
    - nutty
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 15
        reagents:
        - ReagentId: PeanutOil
          Quantity: 10
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/peanut.rsi
  - type: Produce
    seedId: peanuts
  - type: Tag
    tags:
    - Nuts
  - type: SpawnItemsOnUse
    items:
    - id: FoodPeanut
      amount: 2 # give two peanuts per plant
    sound:
      path: /Audio/Effects/packetrip.ogg

- type: entity
  name: peanut
  parent: FoodProduceBase
  id: FoodPeanut
  description: A delicious and salty peanut out of its shell.
  components:
  - type: FlavorProfile
    flavors:
    - creamy
    - nutty
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 7
        reagents:
        - ReagentId: PeanutOil
          Quantity: 2
        - ReagentId: Nutriment
          Quantity: 5
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/peanut_raw.rsi
  - type: Tag
    tags:
    - Nuts

- type: entity
  name: strawberries
  parent: FoodProduceBase
  id: FoodStrawberry
  description: A delectable strawberry, its berry nice to meet you.
  components:
  - type: FlavorProfile
    flavors:
    - strawberry
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 11
        reagents:
        - ReagentId: Nutriment
          Quantity: 5
        - ReagentId: Vitamin
          Quantity: 4
  - type: Sprite
    sprite: _Floof/Objects/Specific/Hydroponics/strawberry.rsi
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: strawberry
  - type: Extractable
    juiceSolution:
      reagents:
      - ReagentId: StrawberryJuice
        Quantity: 10
  - type: Tag
    tags:
    - Fruit # needs its own tag probably
  - type: FoodSequenceElement
    entries:
      Taco: Strawberry
